ARG CONDA_VER=latest
ARG OS_TYPE=x86_64
ARG PY_VER=3.10

FROM debian:11.7-slim as base
RUN apt-get update && apt-get install -yq curl wget jq vim
RUN apt-get install -yq software-properties-common

# Use the above args 
ARG CONDA_VER
ARG OS_TYPE

# Install miniconda to /miniconda
RUN curl -LO "http://repo.continuum.io/miniconda/Miniconda3-${CONDA_VER}-Linux-${OS_TYPE}.sh"
RUN bash Miniconda3-${CONDA_VER}-Linux-${OS_TYPE}.sh -p /miniconda -b
RUN rm Miniconda3-${CONDA_VER}-Linux-${OS_TYPE}.sh
ENV PATH=/miniconda/bin:${PATH}
RUN conda update -y conda
RUN conda init
RUN pip3 install tqdm

FROM debian:11.7-slim as final
COPY --from=base / /
ENV PATH=/miniconda/bin:${PATH}
CMD python3 -c "import tqdm"
